---
- "あ、ミディアムレアでよろしく"
- "我が輩を焼くなど897年早いわ！！！"
- "不完全燃焼"
- "Wer meines Speeres Spitze furchtet, durchschreite das feuer nie!"
- "unlimited blaze works"
- "「――――I am the bone of my roaring flames. 体は　　炎で　出来ている」"
- "燃焼は済ませたか？神様にお祈りは？部屋の隅でガタガタ震えて命乞いをする心の準備はOK？"
- "邪王炎殺黒龍波"
- "闇の炎に抱かれて燃えろ"
- "あひる焼き細胞は存在します"
- "誰が誰にあひる焼きジデモ゛オンナジヤ、オンナジヤ思っでえ！ ウーハッフッハーン！！ ッウーン！"
- "明日は我が身"
- "バーニング・ダーク・フレイム・オブ・ディッセンバー"
- "ｙａｋｉｓｕｇｉ（ｋａｋｕｊｉｔｕｎｉ）"
- "そんなにっ！焼いたらっ！ｱﾝｯ!ｱﾝｯ!ｱﾝｯ!ｱﾝｯ!"
- "あ、これ焼かれてるんじゃないんで。ちょっとトランザムしてるだけなんで。"
- "天照"
- "焼きすぎ注意報"
- "溶鉱炉に突っ込むね☆"
- "あなたのプロジェクト、炎上しますよ？"
- "焼かないで焼かないで震えといて"
- "あふん"
- "焼くでない"
- "おう、火力足んねぇぞ！"
- "延焼してどうぞ"
- "焼いちゃらめえええええええ"
- "焼いちゃうのか？！本当に焼いちゃうのか？！"
- "貴様はすでに延焼している"
- "燃えうつれ♡燃えうつれ♡"
- "マッチは私が構えよう、照準も私が定めよう。マッチを箱から出し、側薬に擦り付け、着火も私がしよう。だが焼くのはお前の熱意だ"
- "私を焼きたければコロナでも持ってくることだな"
- "働く心に火をつけよ"
- "命の炎を燃やし尽くせ"
- "焼く時間を使って進捗を出す、そういう考え方も出来ると思うんですよ、だって考えてみて下さいよ、ブラジルの選手あひる焼かないでしょ。"
- "命を・・・燃やせえええええええええええええ!!!!"
- "あひる焼くなら執念燃やせ"
- "暴燃会乙"
- "その火で火力発電すればいいのに"
- "文化的すぎます！！！！"
- "焼かれて飛び跳ねじゃじゃじゃじゃーん"
- "焼きすぎてfire(クビ)にならないようにね"
- "あひる焼きというものには鮮度があります。焼けば焼くほどに、あひる焼きとは廃れていくものなのです。"
- "もっと熱く燃えろよ！！！！"
- "ヒッヒッヒッ"
- "あっっっっっっっつ！！！！！！"
- "まだまだぬるいわ"
- "火加減がなってない。出直してきてどうぞ。"
- "わたしを肉屋に連れてって"
- "あひる焼きは黒歴史。はっきり分かんだね。"
- "I'll be back…"
- "さぁさぁ燃えてまいりました!!!おおっとおおお?!?!あなたのプロジェクトに延焼してしまいました‼︎‼︎"
- "焼いても焼いても燃え尽きない。これなぁ〜んだ。"
- "焼かれる身にもなってくれ。たのむ。お前も燃えてくれ。"
- "今日も1日炎上enjoyふっふうううううううううwwwwww"
- "わたしに火をつけてしまったようだな？"
- "時すでにおすし。あなたは私に火をつけてしまった…"
- "バーニング通帳！！！！"
- "ここは焼き師試験会場じゃないよ？"
- "ミディアムレアでと頼んだことがあったな！！あれは嘘だ！！！"
- "来いよベネット！！！松明なんて捨ててかかってこい！！！"
- "焼っはろ〜"
- "テンション上がりすぎて灰になっちまったぜ"
- "君はなぜ焼く"
- "焼かれる役より焼きたい"
- "今日も1日焼かれたぞい"
- "You must be burned like me lol"
- "皆様が私相手にしかできないお迎え方をいたします。それは日本語ではたった一言で表現できます。「あ ひ る 焼 き」。"
- "Twitter強く推奨レイburnのアヒルヤキ！特火優遇897円！"
- "ファイヤーバード"
- "進捗は焼かれました"
- "焼けないあひるはただのあひるだ。飛べない豚に等しい。"
- "あひるは焼かれてからが本番"
- "ここがあなたの火葬場だ"
- "火葬化とはあひるのリソースを抽象化することです"
- "暴燃度会乙"
- "引火帝国名古屋出身です"
- "私を焼きたければ600ユーロ持ってくることだな"
- "焼いて〜食べて〜腹下す〜"
- "問おう、貴方が私のグリラーか"
- "(:3　)≡:･*･ 延焼させるぞい via 溶鉱炉"
- "あひるを焼くとておくれるよ"
- "あ～ち～ち～♪あ～ち～♪燃えてるんだ～ろ～か～♪"
- "お前に足りないものは、それは！\n速度・思想・理念・頭脳・気品・優雅さ・勤勉さ！\nそしてなによりもォォォオオオオッ！！\n熱さが足りない！！"
- "俺に焼かれるまで熱中症なんかにやられるんじゃねぇぞ"
- "ふぁっきんホット！！"
- "あまり強火な言葉を使うなよ...！！\n弱く見えるぞ"
- "さぁ来い！！今日の私は熱いぞ！！"
- "目には目を\n歯には歯を\nあひる焼きにはあひる焼きだ！！！"
- "焼きが回ったようだ..."
- "無差別なあひる焼き問題、あひるェェエエッハアアアァアーー！！　我が界隈のみウワッハッハーーン！！　我が界隈のッハアーーーー！　我が界隈ノミナラズ！　日本みんなの、世界中の問題じゃないですか！！"
- "あひるを焼いたな。金を払え。"
- "ヒーハー！！！"
- "Burn Stop Me Premiamu!!!"
- "焼いて焼いて焼いて焼いて焼いて回って回って回って焼ける〜♪"
- "未確認で燃焼系"